pcdshub/pytmc

.travis.yml, README.rst, pytpy/tests/test_initial.py
Project has been configured with basic travis and codecov support. Doctr, Landscape coming soon
=> Travis, Codecov support added 

requirements.txt
I missed the alabaster package when previously cleaning out the requirements file.
=> BLD: I don't think alabaster is necessary

pytmc/bin/makerecord.py, pytmc/bin/xmltranslate.py, pytmc/xml_collector.py, pytmc/xml_obj.py, tests/test_xml_collector.py
Fix broken CLI interface. The issue with pragma stopping has been fixed.
Currently there still remains a bug with PV rendering. Often extra colons will be drawn when empty PV fields are given. This should be sufficient in a testing environment but I'll have the issue cleaned up before finishing this PR.
=> Fixes 2 20

pytmc/xml_obj.py, tests/conftest.py, tests/test_xml_obj.py
Allow semicolons for breaking pragma configuration lines.
=> Regex upgrade

setup.py
=> BLD: check minimum Python version

pytmc/xml_collector.py
=> FIX: remove by item, not index

pytmc/xml_collector.py, tests/test_xml_collector.py
Split methods that guess multiple fields for simplicity.
Removes a fair amount of boilerplate try/except in the guess methods.
=> REF: add _skip_if_field_set decorator

.travis.yml, docs/source_code.rst
One straggler commit I forgot to push as part of #85, plus (hopefully) a fix to building/publishing docs.
=> CI: fix docs

pytmc/bin/stcmd.py
Defaults to the current working directory
=> ENH: allow templates from outside the package (pytmc stcmd)

pytmc/bin/stcmd.py
see https://github.com/pcdshub/ads-ioc/pull/8
=> ENH: update default binary name to new standard

pytmc/record.py
=> FIX: tse/pini settings for output records

pytmc/parser.py
Closes issue in separate repo https://github.com/pcdshub/pcdswidgets/issues/22
=> FIX: type extensions are now respected

pytmc/bin/stcmd.py
There are some finer points about this that need to be discussed at some point, but for now this PR just fixes the usage of a pytmc pragma on an FB_MotionStage in conjunction with the stcmd generation script:
Bug:
```
Traceback (most recent call last):
...
File "/reg/g/pcds/epics/R7.0.2-2.0/ioc/ads-ioc/v0.0.2/iocBoot/templates/st.cmd.template", line 63, in top-level template code
epicsEnvSet("MOTOR_PREFIX",    "{{motor|epics_prefix}}")
File "/usr/local/lib/python3.7/site-packages/pytmc/bin/stcmd.py", line 137, in epics_prefix
return get_name(obj, user_config)[0]
File "/usr/local/lib/python3.7/site-packages/pytmc/bin/stcmd.py", line 118, in get_name
config = pragmas.squash_configs(*configs)
File "/usr/local/lib/python3.7/site-packages/pytmc/pragmas.py", line 190, in squash_configs …
```
=> FIX: pragmas on motionstage

.gitmodules, pytmc/bin/stcmd.py, pytmc/parser.py, pytmc/templates/stcmd_default.cmd, tests/test_commandline.py, tests/test_motion.py, tests/test_project.py
closes #98 
based on #118, so merge that one first
DUT_MotionStage is the interface we're connecting to in the IOC, not FB_MotionStage. This switches some of the symbol stuff to the data type, which simplifies the handling a bit.
=> ENH: switch to using DUT_MotionStage

pytmc/bin/db.py, pytmc/bin/debug.py, pytmc/bin/pragmalint.py, pytmc/bin/stcmd.py, pytmc/pragmas.py, pytmc/record.py, tests/test_lint.py
Closes #134 
Closes #127 
Closes #131 
Closes #133 
Closes #132
=> ENH/FIX: Better linting, debug tool fixes, $ handling, ... and more!

pytmc/templates/asyn_standard_record.jinja2
=> FIX: sort autosave fields

conda-recipe/meta.yaml
Just doing the easy part
closes #149
=> BLD: rename pypdb to epics-pypdb in conda recipe

pytmc/record.py, pytmc/templates/asyn_standard_record.jinja2
=> ENH: support record aliases + default description

docs/pragma_usage.rst, pytmc/bin/db.py, pytmc/bin/pragmalint.py, pytmc/bin/pytmc.py, pytmc/pragmas.py, pytmc/record.py, tests/test_archive.py, tests/test_commandline.py, tests/test_lint.py, tests/test_xml_collector.py
Closes #139
See the related issue + docs for further information.
=> ENH: add preliminary archive file support

pytmc/bin/summary.py
=> FIX: sort boxes in summary by ID

pytmc/bin/stcmd.py, pytmc/bin/summary.py, pytmc/parser.py, pytmc/templates/stcmd_default.cmd
- Add `is_pointer` property to `Symbol` tmc items to check if they are pointers or not
- Add aux info and expand `pytmc summary` info to include pointer/array text
- filter motors down to skip pointers for the stcmd generation
closes #168
=> ENH/FIX: Pointers

pytmc/bin/stcmd.py
=> BUG: pass arguemnt to db.process

pytmc/bin/pragmalint.py, pytmc/pragmas.py, pytmc/record.py, tests/test_lint.py, tests/test_xml_collector.py
Closes #166 
I think this could pair with an lcls-twincat-general set of structures, as indicated in the issue.
cc @ghalym
=> ENH: PV linking via DOL/OMSL + CPP input link

pytmc/record.py, tests/test_xml_collector.py
closes #190 
alternative to #192
=> MNT: switch default value to most common case

MANIFEST.in
=> BLD: add license to manifest

.travis.yml, conda-recipe/build.sh, conda-recipe/meta.yaml
Updated conda recipe as well
Let's see what happens 🤷‍♂️
=> CI: try new shared configurations

pytmc/bin/db.py
=> FIX: remove_config_field no longer exists

pytmc/bin/summary.py, pytmc/parser.py, pytmc/pragmas.py
Additionally:
`FIX: some tmc files are missing a DataArea; create one for symbols if needed.`
I was previously unaware that DataTypes can be defined at the .tsproj level until I found this in the case of lcls-twincat-general: https://github.com/pcdshub/lcls-twincat-general/blob/4f45e54ff29676050368109dffca0f340c7054ac/LCLSGeneral/LCLSGeneral.tsproj#L149-L174
This adds summary support, and pairs with ads-deploy PR https://github.com/pcdshub/ads-deploy/pull/15
Example docs rendered output:
=> ENH: support enumeration of tsproj project-defined data types

docs/index.rst, docs/release_notes.rst
Took a bit longer than anticipated - had to start from scratch here.
=> DOC: release v2.7.1 + include release notes in documentation

docs/release_notes.rst
=> DOC: add release notes

pytmc/bin/template.py, pytmc/parser.py
Closes #249
Separates and parses out information from library references, placeholders and resolutions.
Using this to generate PLC version information summaries:
https://github.com/pcdshub/plc-summary/blob/master/docs/source/versions.rst
Need to update ads-deploy for per-project dependency version fixes - as some projects are missing them currently.
=> FIX: rework dependency-related twincat items and templating tools

docs/release_notes.rst
=> DOC: release notes (v2.8.1)

README.rst, conda-recipe/meta.yaml, dev-requirements.txt, docs/index.rst
Remove codecov. We aren't using it and they had a security breach
=> MNT: remove codecov after security breach

docs/release_notes.rst
=> DOC: add release notes for v2.11.0

pytmc/tests/test_xml_collector.py
After opening #278 this reminded me of a local test branch to see if `link` was doing what I thought it should (or if I remembered how I had even designed it, perhaps).
It turns out that it does, fortunately.
Should add some docs to this PR prior to merging.
=> TST: does linking work as expected?

pytmc/bin/db.py
Closes #292 
There's 3 lines of implementation; the remainder is clean-up/annotation:
```python
def by_tcname(record: RecordPackage):
return record.tcname
records.sort(key=by_tcname)
```
I was wrong about the iterative generation of the records as in #292. Finding chains is an iterative process but generating `db` files from the pared down record list is not. So, there's no real performance impact here.
=> REF: sort generated records by TwinCAT symbol name (tcname)

MANIFEST.in, pytmc/tests/conftest.py, pytmc/tests/templates/basic_test.txt, pytmc/tests/templates/smoke_test.txt, pytmc/tests/test_commandline.py
closes #295 probably
see linked issue for details
=> TST: test suite was using old kwarg, swap to new

.github/workflows/standard.yml
(Enabling  GitHub Actions CI for #302)
=> CI: add standard GitHub Actions workflow

docs/source/release_notes.rst, pytmc/parser.py
Follow-up to #331 
I made an error there that caused my fix to be completely skipped.
I've also updated the release notes docs in this PR.
I'm doing one more offline test before I even consider hitting merge.
=> FIX: remove wayward duplicate line from pre-fix
