pytmc/xml_obj.py, tests/conftest.py, tests/test_xml_obj.py
Bugfixes:
- Variable whitespace after the first colon is allowed
- Single line PV's are recognized correctly
- Multiple colons (or any concatenation symbol) are no longer drawn when PV name strings are skipped
=> Regex, Semicolon fix 

setup.py
This should properly include templates in the installed package.
Closes #32
cc @domitto
=> BLD: include templates in installed package

.travis.yml, conda-recipe/build.sh, conda-recipe/meta.yaml, dev-requirements.txt, requirements.txt
I'd like to get this is in so we can start deploying this on `pcds-tag` this will be necessary to include it as part of our standard Python releases
* Setups a CONDA recipe
* Move a few packages around between `requirements` and `dev-requirements`
* Remove the version specifications on the packages
* Use CONDA to build prior to tests on Travis
* Puts machinery in Travis to deploy built packages to `pcds-tag` and `pcds-dev`
=> CONDA Deployment

pytmc/bin/pytmc.py, pytmc/bin/pytmc_debug.py, setup.py, tests/test_linter.py
Although this script has a dependency on `qtpy` (and therefore `PyQt5`/`Qt5`/etc), I think it can be considered optional. I had intended to make a command line-only alternative to the Qt version, but I'm not sure it's worthwhile.
=> ENH: add pytmc-debug GUI tool for inspecting pytmc processing

pytmc/bin/stcmd.py
Noticed this with @zllentz - it found some `FB_MotionStage` symbols from the wrong PLC.
=> FIX: symbols should be searched for in virtual PLCs, not project-level

pytmc/bin/stcmd.py, pytmc/bin/summary.py, pytmc/parser.py
cc @zllentz - as we ran into this yesterday.
Output from the project during the demo:
```
$ pytmc summary --plcs tests/projects/motion-demo/motion-demo/motion-demo/motion-demo.tsproj
PLC Project (1): Demo1
======================
Project path: /Users/klauer/docs/Repos/pytmc/tests/projects/motion-demo/motion-demo/motion-demo/Demo1/Demo1.plcproj
TMC path:     /Users/klauer/docs/Repos/pytmc/tests/projects/motion-demo/motion-demo/motion-demo/Demo1/Demo1.tmc
AMS ID:       5.57.239.146.1.1
IP Address:   5.57.239.146 (* based on AMS ID)
Port:         851
Source files:
1.) /Users/klauer/docs/Repos/pytmc/tests/projects/motion-demo/motion-demo/motion-demo/Demo1/PlcTask.TcTTO
2.) /Users/klauer/docs/Repos/pytmc/tests/projects/motion-demo/motion-demo/motion-demo/Demo1/POUs/Main.TcPOU
POUs:
1.) Main
PLC …
```
=> FIX: AMS ID is on the TopLevelProject

.travis.yml, dev-requirements.txt
Fixes the issues we are seeing install Qt via `pip` on Travis. Don't really know why the pip version was working but I know that we will deploy this system with the CONDA version so it is probably best to test with it on the CI.
As a side note, I removed Qt from all of the requirements. Installing it is really a mess so I think it is probably best to just depend on `qtpy` and leave the actual `Qt` installation as an individual choice. It is almost impossible to have a setup that works with both `pip` and `CONDA` if we do not go this route.
=> CI: Qt installation on Travis

pytmc/record.py, tests/test_xml_collector.py
Closes #97 
Reference:
https://github.com/pcdshub/twincat-ads/blob/24f81b23c52355ea0088bebd509680470e5f24b5/adsApp/src/adsAsynPortDriver.cpp#L3895
Tested on IOC (now that I finally have access with my VM!)
```
ADS_TST:Str this is a test
ADS_TST:Str_RBV 2019-08-13 16:10:14.993000 this is a test
```
=> FIX: strings only work with asynInt8Array with twincat-ads

pytmc/bin/iocboot.py, pytmc/bin/pytmc.py, pytmc/bin/stcmd.py, pytmc/templates/stcmd_default.cmd
Couples with pcdshub/ads-ioc#7
General idea is the following:
```bash
$ pytmc iocboot /path/to/plc.tsproj /path/to/ads-ioc/iocBoot/templates/
$ cd ioc-plc-name
$ vim Makefile
$ make
$ ./st.cmd
```
Remaining:
=> ENH: pytmc-iocboot

pytmc/pragmas.py
This gets rid of two kinds of invalid symbols:
- duplicates, where symbol leafs are doubled-up with their containing
structure
- invalid symbols, where there is not a complete pragma path from
top-level down to the symbol itself
The tmc file can have duplicate or bogus pytmc symbol entries for anything that is marked as an input or an output variable. The correct symbols to use are the symbols with only two dot-separated fields, such as `GVL.bInput` or `Main.stStruct`, not `Main.stStruct.bOutput` which is actually a double-count.
=> FIX: Ignore invalid pytmc symbols

pytmc/parser.py, pytmc/pragmas.py, pytmc/record.py
Discovered by @ZLLentz, this bug caused arrays to be represented as scalar records (i.e., not `waveform`) in the EPICS db.
This now generates what appears to be correct to me:
```
record(waveform, "TST:PPM:SPM:VOLT_BUFFER_RBV"){
field(PINI, "1")
field(TSE, "-2")
field(INP, "@asyn($(PORT),0,1)ADSPORT=851/Main.fbPPM.stPPM.stPowerMeter.fVoltageBuffer?")
field(DTYP, "asynFloat64ArrayIn")
field(SCAN, "I/O Intr")
field(FTVL, "DOUBLE")
field(NELM, "1000")
}
record(waveform, "TST:PPM:SPM:MJ_BUFFER_RBV"){
field(PINI, "1")
field(TSE, "-2")
field(INP, "@asyn($(PORT),0,1)ADSPORT=851/Main.fbPPM.stPPM.stPowerMeter.fCalibMJBuffer?")
field(DTYP, "asynFloat64ArrayIn")
field(SCAN, "I/O Intr")
field(FTVL, "DOUBLE")
field(NELM, "1000")
}
```
(This also shows we have a _lot_ of holes in the test suite, which …
=> FIX: arrays and string waveform NELM

pytmc/bin/db.py
Closes #96 
Looks like:
```sh
$ pytmc db TC_project/TwinCAT\ Project1/TwinCAT\ Project1/Untitled1/Untitled1.tmc
ERROR:pytmc.bin.db:Duplicate records encountered:
ADS_TST:ReadOnly:Str (2)
ADS_TST:ReadOnly:bArray (2)
ADS_TST:ReadOnly:bState (2)
```
=> ENH: error on duplicate records generated

pytmc/record.py
https://slaclab.github.io/pytmc/pragma_usage.html#io
=> FIX: default io type should be io, as per the docs

pytmc/bin/db.py
The behavior of the duplicate record checker from `pytmc db` meant that pytmc could bail silently, as discovered by @domitto.
Now, it will result in the following:
```
$ pytmc db GmdPlc-20190822.tmc
ERROR:pytmc.bin.db:Linter errors - failed to create database. To create the database ignoring these errors, use the flag `--allow-errors`
Traceback (most recent call last):
File "/Users/klauer/docs/Repos/pytmc/pytmc/bin/db.py", line 194, in main
show_error_context=not no_error_context,
File "/Users/klauer/docs/Repos/pytmc/pytmc/bin/db.py", line 118, in process
raise LinterError(message)
pytmc.bin.db.LinterError: Duplicate records encountered:
fb_EM1K0_GMD_GCC_10:PRESS (2)
fb_EM1K0_GMD_GCC_20:PRESS (2)
fb_EM1K0_GMD_GCC_30:PRESS (2)
fb_EM1K0_GMD_GCC_40:PRESS (2)
fb_EM1K0_GMD_GCC_50:PRESS (2) …
```
=> FIX: be better about showing linter errors to user

pytmc/bin/debug.py
Duplicate records will not block the dialog from showing
=> FIX: allow errors when showing debug dialog

.gitmodules, pytmc/bin/pragmalint.py, pytmc/bin/pytmc.py, pytmc/bin/summary.py, pytmc/bin/util.py, pytmc/pragmas.py, tests/test_commandline.py, tests/test_project.py
Pragmas in TwinCAT are syntactically strange and difficult to type, and TwinCAT is rather specific about what it's looking for - silently ignoring the pragma altogether if it doesn't match up.
So, the idea here is to give a tool to lint the project to find pragma errors before they get further down the line.
I'm not 100% sure about the regex given here, but it at least caught some problematic ones in my local tests.
Example:
```
$ pytmc pragmalint ~/Repos/L2SI-Vacuum-Lib/L2SIVacuumLib.tsproj 
PLC Project (1): L2SIVacuum
===========================
ERROR:pytmc.bin.pragmalint:Linter error:
DUTs/Valves/ST_VGC.TcDUT:line 54:     {attribute 'pytmc' :=
'pv: Ext_ILK_OK ;
field: ZNAM NOT OK ;
field: ONAM OK ;
io: i ;
'}
ERROR:pytmc.bin.pragmalint:Linter error:
DUTs/Valves/ST_VGC.TcDUT:line 134: …
```
=> ENH: add pragma linter utility

pytmc/pragmas.py
q_iRawPosition in plc_kfe_xgmd_vac.tmc
`L2SI_Vacuum_Library.ST_VCN`:
```
<SubItem>
<Name>q_iRawPosition</Name>
<Type>INT</Type>
<Comment><![CDATA[Position control ]]></Comment>
<BitSize>16</BitSize>
<BitOffs>32</BitOffs>
<Properties>
<Property>
<Name>pytmc</Name>
</Property>
</Properties>
</SubItem>
```
=> FIX: pragma can be None, somehow

pytmc/bin/iocboot.py
The IOC naming convention has dashes, e.g. `ioc-fee-motion`, but these are not allowed in the plc project names because TwinCAT forbids it.
The idea is that we use underscores instead in the plc name and convert them to dashes in the ioc name. This was discussed at some point but never made it into the library here.
=> ENH: replace underscores in plc names with dashes in ioc name

pytmc/parser.py, pytmc/pragmas.py, pytmc/record.py, tests/test_xml_collector.py
```
Special handling for arrays of complex types will unroll the array into
individual elements.  That is, `arr : ARRAY [1..5] of ST_Structure` will be
unrolled into `arr[1]` through `arr[5]`.
```
* Added some additional docstrings that were rather lacking
* Zero-padding defaults to 1 more than needed
- 9 elements will be unrolled as :01 to :09
- 86 elements will be unrolled as :001 to :086
- Configurable using `expand` pragma on the array. e.g., `expand: _ELEMENT_%.3d` -> `prefix_ELEMENT_003`
=> ENH: unroll arrays of complex types + enums

pytmc/parser.py
Using the search for two different strings method fails when the axis
count exceeds 10, since searching for M1 also collides with M10, M11,
M12, etc.
We couldn't use the precise name when we were targeting FB_MotionStage,
but now we can because DUT_MotionStage has a clearly defined namespace.
=> FIX: Use precise link name

pytmc/bin/summary.py, pytmc/parser.py
Moving the project-from-sln regex in from ads-deploy-docker.
=> ENH/FIX: allow solution file to be passed in for `pytmc summary`

pytmc/bin/stcmd.py
Pairs with https://github.com/pcdshub/ads-ioc/pull/15
Allows access to NC parameters, including all axis IDs
=> ENH: allow access to NC in templates

pytmc/parser.py
pytmc expanded the T_MaxString to a basic data type, which did not have a pytmc pragma and was therefore ignored. This could be considered a workaround (or, ahem, hack). Confirmed working with the PMPS library.
Fancy "typedefs" such as this may trip us up again in the future and perhaps require a bit more thought.
=> FIX: make T_MaxString:=STRING(255)

pytmc/bin/summary.py
Closes pcdshub/ads-deploy#6
Declaration/implementation sections in source code files is allowed to be `None`. This fixes `pytmc summary` to not bail in such cases.
I'm sure we'll find similar issues like these as time goes on and more projects are run through the parser. Unless the issue reports get out of hand, I'd rather fix them one-by-one instead of handling such exceptions generically.
=> FIX: declaration/implementation text can be None

pytmc/parser.py
The UTF-8 BOM was causing pytmc running on Windows to bail immediately with the message:
```
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
```
Enums were apparently also being ignored in some (all?) cases in recent builds. b79f4a9 attempts to fix that by ensuring `DataType.walk()` is always yielding something, allowing for the creation of chains.
Confusing implementation detail: enums should be seen to pytmc in a way similar to a built-in type (UINT + some metadata), and as `BuiltInType` yields `[]` for `walk()` this PR brings it in line with that.
~One test is now failing as a previously-ignored enum is now found to be duplicated...~ The pragma was already fixed upstream; updated to master in 53aa27f.
=> FIX: enums; utf8 BOM on win32

MANIFEST.in, requirements.txt, setup.py
Closes #59 🎆 
1. Made our own release of pyPDB to pypi - https://pypi.org/project/epics-pypdb/  - had to rename due to a package naming conflict
2. Fixed manifest + install requirements
3. Released the latest version to pypi - https://pypi.org/project/pytmc/
`pip install pytmc` _should_ work now...
=> DIST: fix requirements + manifest for pypi installation

docs/pragma_usage.rst, pytmc/record.py, pytmc/templates/asyn_standard_record.jinja2, tests/test_record.py
Closes #41 
Defaults are specified in classes from `pytmc.record`. These can be overridden by using specific keys in the pragmas:
```
To apply to either input or output records, pragma keys `autosave_pass0`
or `autosave_pass1` can be used.
To only apply to input records, pragma keys `autosave_input_pass0`
`autosave_input_pass1` can be used.
To only apply to output records, pragma keys `autosave_output_pass0`
`autosave_output_pass1` can be used.
```
More info in the documentation commit (see diff).
I have not given the defaults much thought, but with this PR as a basis we can fill in those details later.
=> ENH: add autosave support

pytmc/bin/summary.py
Just for readability. See example below.
Before:
```
$ pytmc summary ../lcls-twincat-general/LCLSGeneral/LCLSGeneral.tsproj  --plcs
PLC Project (1): LCLSGeneral
============================
Project path: /Users/klauer/docs/Repos/lcls-twincat-general/LCLSGeneral/LCLSGeneral/LCLSGeneral.plcproj
TMC path:     /Users/klauer/docs/Repos/lcls-twincat-general/LCLSGeneral/LCLSGeneral/LCLSGeneral.tmc
AMS ID:
IP Address:    (* based on AMS ID)
Port:         851
Source files:
1.) /Users/klauer/docs/Repos/lcls-twincat-general/LCLSGeneral/LCLSGeneral/Data types/Misc/ST_EcDevice.TcDUT
2.) /Users/klauer/docs/Repos/lcls-twincat-general/LCLSGeneral/LCLSGeneral/Data types/Misc/ST_FbDiagnostics.TcDUT
3.) /Users/klauer/docs/Repos/lcls-twincat-general/LCLSGeneral/LCLSGeneral/Data types/Misc/ST_System.TcDUT
4.) …
```
=> MNT: show summary paths relative to the project root

pytmc/bin/db.py, pytmc/bin/debug.py, pytmc/pragmas.py, pytmc/record.py, tests/test_integrations.py
Adds a category to the debug interface to show TwinCAT variable chains that have *not* been fully rendered to records. Alterations have been made to the chain generation procedures to make it less dependent upon record generation to allow flawed records to be generated.
closes #147 
Also addresses some oddities in the debug interface's config_info table not drawing properly. 
closes #158
=> Enh: show incomplete pragmas

pytmc/pragmas.py, tests/test_xml_collector.py
The off-by-one error in array bounds fix in #169 created a new off-by-one error in the code introduced in #121 that was relying on the previously off-by-one value. This fixes the issue.
=> FIX: off by one error in complex array unrolling

pytmc/bin/code.py, pytmc/bin/pytmc.py, pytmc/bin/summary.py, pytmc/code.py, pytmc/parser.py, tests/test_commandline.py
* Adds `POU.get_source_code` method
* Provides easier access to Actions (e.g., `FB_Name.Action();` - equivalent of Python methods, pretty much)
(Aside: this PR pairs with my airplane/weekend side-project that allowed me to somewhat stave off jet lag, https://github.com/klauer/blark/ - an IEC61311-3 structured text parser using an Earley parser from [Lark](https://github.com/lark-parser/lark/). Having a full parser for structured text POUs may allow us to do some sort of static analysis, generate more thorough documentation, and who knows what else. It parses _almost_ all of the PCDS code I've downloaded locally, with a few exceptions...)
=> ENH: full source code + access to actions

docs/pragma_usage.rst, pytmc/templates/asyn_standard_record.jinja2
Closes #176 
Autosave fields seems to be lacking tests (future TODO)
Also for the future: we might consider using `makeAutosaveFileFromDbInfo` in ads-ioc to have more control over autosave's functionality
=> FIX: autosave info node names incorrect

pytmc/bin/db.py
This is for convenience and also will be required for upcoming ads-ioc changes...
=> ENH: allow pytmc db to work using a tsproj file

.gitmodules, pytmc/bin/stcmd.py, pytmc/parser.py, tests/conftest.py, tests/test_commandline.py
I don't have much faith in the correctness of this, but it appears to load all (valid) tsproj files I have on hand, including those in the test suite.
* Added https://github.com/n-wbrown/lcls-plc-kfe-gmd-vac/commit/4b4105124f5ca00aac6353d7b8c58e12ac4ba333 as a submodule, which should close #179
=> FIX: config/io path loading

pytmc/parser.py
Referenced global variable in an EnumInfo block sometimes does not generate the Enum value field:
Code:
```vhdl
VAR_GLOBAL CONSTANT
gc_iSizeOfGGOArray : INT := 50;
gc_GaugeValidState :  INT := 10;
END_VAR
TYPE E_PressureState :
(
//Valid States (Positive)
Valid := gc_GaugeValidState, // gc_GaugeValidState set in "Global Variable Folder: Constants"
ValidHi    := 11, //gc_GaugeValidState + 1,
ValidLo    := 12, //gc_GaugeValidState + 2,
// Invalid states
PressInvalid    := 1, //gc_GaugeValidState - 1,
GaugeDisconnected     :=   2, //gc_GaugeValidState -2,
OoR  := 6, //gc_GaugeValidState -6,
// Ion gauges
Off        := 3, //gc_GaugeValidState - 3,
Starting   := 4 //gc_GaugeValidState - 4
) INT;
END_TYPE
```
Relevant portion of the TMC:
```
<EnumInfo>
<Text>Valid</Text>
<Comment><![CDATA[ …
```
=> ENH: warn if Enum value missing

pytmc/bin/db.py, pytmc/pragmas.py
Provide the name of TwinCAT variable when the db.process fails to build a record from the chain. 
Example output:
```
ERROR:pytmc.bin.db:Error creating record: GVL_GMD.fb_EM1K0_GMD_GPI_10.PG.eState 'EnumInfo' object has no attribute 'Enum'
```
Open to feedback as always.
=> Describe process error

pytmc/record.py, tests/test_xml_collector.py
This is subject to change and as such I don't want it to be documented just yet (I know, I know...)
Hoping to get this in for a paired PR in lcls-twincat-general shortly (assuming tests pass).
=> ENH: special syntax to allow for referring to PV name in linked variable

pytmc/record.py, pytmc/templates/asyn_standard_record.jinja2
Pairs with https://github.com/pcdshub/ads-ioc/pull/33
Still can generate `.archive` files separately, but also adds info nodes.
Example from an old test tmc:
```
record(bi, "fb:EM1K0:GMD:PRT:40:ALARM_OK_RBV") {
... 
info(archive, "VAL")
}
record(bi, "fb:EM1K0:GMD:PRT:40:RUN_DI_RBV") {
...  
info(archive, "monitor 2: VAL DESC")
}
```
=> REF: rework the archive settings to add info(archive) nodes

pytmc/bin/pytmc.py, pytmc/bin/summary.py, pytmc/bin/util.py, pytmc/pragmas.py
* Catch overall symbol-level pragma parsing failures and annotate with symbol name
* Catch chain-level failures and annotate with chain names
Result looks like this:
```
ERROR:pytmc.bin.db:Error creating record: Symbol GVL_FEE_Device.MR1K4_SOMS_PIP_01 failure: Found invalid pragma line(s):
--> | MR1K4_SOMS_PIP_01
ERROR:pytmc.bin.db:Error creating record: Symbol GVL_FEE_Device.ST1K4_TEST_PIP_01 failure: Found invalid pragma line(s):
--> | ST1K4_TEST_PIP_01
ERROR:pytmc.bin.db:Error creating record: Symbol GVL_FEE_Device.ST2K4_BCS_PIP_01 failure: Found invalid pragma line(s):
--> | ST2K4_BCS_PIP_01
ERROR:pytmc.bin.db:Error creating record: Symbol GVL_FEE_Device.ST3K4_PPS_PIP_01 failure: Found invalid pragma line(s):
--> | ST3K4_PPS_PIP_01
ERROR:pytmc.bin.db:Error creating record: Symbol …
```
=> FIX: pragma parse failure with information about symbol/chain

pytmc/record.py, pytmc/templates/asyn_standard_record.jinja2
Automatic "middle" truncation of DESC field has been in place for the default description, as follows:
`GVL_GMD.fb_EM1K0_GMD_PRT_40.stPump.i_xAlarmOK` would become a description of `ads:GVL_GMD.fb_EM1K0...stPump.i_xAlarmOK` to fit within the 40 character field limit. This PR removes the `ads:` prefix, which further shortens the displayable characters.
The above was not generically applied to user-specified descriptions. This caused many instances of db parsing failures on IOC boot.
Rather than do as suggested in #196 making this either a warning/error, the DESC field itself is truncated silently, but also included in full-form as a comment in the database file.
Before
--------
```
record(bi, "EM1K0:GMD:PRT:40:ALARM_OK_RBV") {
field(DESC, "ads:GVL_GMD.fb_EM1K0...stPump.i_xAlarmOK")
...
} …
```
=> Tweaks for handling the DESC field

pytmc/record.py
pytmc's pragma syntax only allows for a general `"field: FIELDNAME FIELDVALUE"`-style specification, which gets applied to both the input and output record.
We can apply a bit of knowledge about the records and their fields to allow for this form to remain valid, but also only apply the fields to the appropriate records.
The fields in this PR were generated by way of pyPDB and the caproto test suite. A messy but functional:
```python
$ ipython -i caproto/tests/dbd.py
In [1]: dbd = DbdFile.parse_file('caproto/tests/reference-dbd/motorSim.dbd')
In [2]: def compare(input_rec, output_rec):
...:     input_fields = set(dbd.field_metadata[input_rec])
...:     output_fields = set(dbd.field_metadata[output_rec])
...:     output_only = list(sorted(set(output_fields) - set(input_fields)))
...: …
```
=> FIX: some fields only apply to input/output records

pytmc/bin/summary.py, pytmc/parser.py, pytmc/pragmas.py, pytmc/record.py, tests/test_commandline.py
Still requires `.tmc` file, but may help with validation of pcdsdevices PRs.
Sample (clipped) output:
```
$ pytmc summary L2SIVacuumLib.tsproj --types --filter-type ST_* --filter-type FB_*
...clipped...
Data type ST_FFVeto
-------------------
$(PREFIX):Activate
$(PREFIX):Activate_RBV
$(PREFIX):Active_RBV
$(PREFIX):Deactivate
$(PREFIX):Deactivate_RBV
$(PREFIX):Duration
$(PREFIX):Duration_RBV
$(PREFIX):ElapsedTime_RBV
...clipped...
Data type FB_MKS422
-------------------
$(PREFIX):AT_VAC_RBV
$(PREFIX):DISC_ACTIVE_RBV
$(PREFIX):HV_DIS_DO_RBV
$(PREFIX):HV_ON_RBV
$(PREFIX):HV_SW
$(PREFIX):HV_SW_RBV
$(PREFIX):ILK_OK_RBV
$(PREFIX):LOGGER_RBV
$(PREFIX):PRESS_AI_RBV
$(PREFIX):PRESS_OK_RBV
$(PREFIX):PRESS_RBV
$(PREFIX):PRO_SP
$(PREFIX):PRO_SP_RBV
$(PREFIX):SP_HYS
$(PREFIX):SP_HYS_RBV …
```
=> ENH: symbol-less data type record information

pytmc/bin/pytmc.py
Closes #201, as I can only assume it's what @n-wbrown ran into.
Saw this on travis:
`qtpy.PythonQtError: No Qt bindings could be found` which apparently does not subclass `ImportError`.
=> FIX: any error makes the sub-command unavailable

pytmc/record.py
Last tag was premature. Tested locally against the KFE project with the following results:
DESC
```
field(DESC, "Internal variable us...V severity in PLC")
```
And:
```
field(DOL, "$(PREFIX)Link:ElectronEnergy:SXU:EPICSLink.SEVR CPP MS")
```
=> FIX: DOL fix follow-up and DESC fix part ocho

pytmc/parser.py
I think this pre-loading and indexing of XTI files will prove a more reliable method.
It loads master on these:
```
lcls-plc-crixs-motion
lcls-plc-crixs-vac
lcls-plc-kfe-arbiter
lcls-plc-kfe-gmd-vac
lcls-plc-kfe-motion
lcls-plc-kfe-rix-motion
lcls-plc-kfe-rix-vac
lcls-plc-kfe-vac
lcls-plc-kfe-xgmd-vac
lcls-plc-lfe-arbiter
lcls-plc-lfe-gem
lcls-plc-lfe-motion
lcls-plc-lfe-motion-kmono
lcls-plc-lfe-optics
lcls-plc-lfe-vac
lcls-plc-liquid-jet
lcls-plc-roving-spectrometer
lcls-plc-tmo-motion
lcls-plc-vls-vac
```
With 2 hash key clashes:
<details>
```
WARNING:pytmc.parser:Found multiple potential matches with the same key: (<class 'pytmc.parser.Box'>, '32', 'box 32 (el6692).xti') => /Users/klauer/docs/Repos/plcs/lcls-plc-kfe-arbiter/Arbiter/_Config/IO/Device 1 (EtherCAT)/Box 28 (CU1128)/Box 32 …
```
=> REF/FIX: box file loading, again

.pre-commit-config.yaml, docs/release_notes.rst, pytmc/bin/db.py, pytmc/parser.py, pytmc/pragmas.py, pytmc/record.py, pytmc/tests/test_integrations.py
* Some GUIDs appear to be implicitly defined (the data type `GUID` itself, `OTCID`, maybe others?)
<details>
<summary>
Fixes at least some instances of missing symbols (hence the updated test)
</summary>
```
> TwinCAT_SystemInfoVarList._AppInfo.AdsPort
> TwinCAT_SystemInfoVarList._AppInfo.AppName
> TwinCAT_SystemInfoVarList._AppInfo.AppTimestamp
> TwinCAT_SystemInfoVarList._AppInfo.BSODOccured
> TwinCAT_SystemInfoVarList._AppInfo.BootDataLoaded
> TwinCAT_SystemInfoVarList._AppInfo.Flags
> TwinCAT_SystemInfoVarList._AppInfo.KeepOutputsOnBP
> TwinCAT_SystemInfoVarList._AppInfo.LicensesPending
> TwinCAT_SystemInfoVarList._AppInfo.LoggedIn
> TwinCAT_SystemInfoVarList._AppInfo.ObjId
> TwinCAT_SystemInfoVarList._AppInfo.OldBootData
> TwinCAT_SystemInfoVarList._AppInfo.OnlineChangeCnt
> …
```
=> ENH/REF: data types by guid, falling back to qualified type name

pytmc/record.py, pytmc/tests/test_xml_collector.py
Closes #231 
Generates records such as:
```
record(waveform, "MR2K3_GPI_1:PRESS_RBV") {
field(DESC, "GVL_DEVICES.MR2K3_GPI_1.PG.rPRESS")
field(SCAN, "I/O Intr")
field(PINI, "1")
field(TSE, "-2")
field(DTYP, "asynInt16ArrayIn")
field(INP, "@asyn($(PORT),0,1)ADSPORT=851/POLL_RATE=1/GVL_DEVICES.MR2K3_GPI_1.PG.rPRESS?")
field(FTVL, "SHORT")
field(NELM, "1000")
field(MPST, "On Change")
field(APST, "On Change")
}
```
cc @slacAWallace
=> REF/ENH: lower archive threshold; set archive/monitor settings on waveforms

pytmc/record.py
closes #235 
This is a workaround fix for autosave pass1 not behaving as expected for records where PINI=0
Implementation:
- Add a method `update_pini_for_autosave` on `EPICSRecord` with an appropriate docstring
- Call this method when creating output records
With the goal of being able to cleanly remove this method if we figure out why the expected behavior did not work at ads-ioc in https://github.com/pcdshub/ads-ioc/issues/65
Resulting diff on my test IOC (extended to show the full record):
```
$ git diff
diff --git a/iocBoot/ioc-tc-mot-example/tc_mot_example.db b/iocBoot/ioc-tc-mot-example/tc_mot_example.db
index 319a356..cd3628b 100644
--- a/iocBoot/ioc-tc-mot-example/tc_mot_example.db
+++ b/iocBoot/ioc-tc-mot-example/tc_mot_example.db
@@ -13,6 +13,7 @@ record(ai, …
```
=> FIX: fix autosave pass1 by setting PINI=YES

docs/release_notes.rst, pytmc/bin/db.py, pytmc/linter.py
Closes #221 
Looks like:
```
$ pytmc db arb.tmc
ERROR:pytmc.bin.db:Linter errors - failed to create database. To create the database ignoring these errors, use the flag `--allow-errors`
Traceback (most recent call last):
File "/Users/klauer/docs/Repos/pytmc/pytmc/bin/db.py", line 293, in main
debug=debug,
File "/Users/klauer/docs/Repos/pytmc/pytmc/bin/db.py", line 155, in process
raise ex
pytmc.bin.db.LinterError: Records exceeding the maximum length of 60 were found:
$(PREFIX)FFO:01:FF:001:Info:PathOFDIJOIWEJFOIJWEFOIJWEOFIJWEOIFJWEOIFJ_RBV
$(PREFIX)FFO:01:FF:002:Info:PathOFDIJOIWEJFOIJWEFOIJWEOFIJWEOIFJWEOIFJ_RBV
```
=> ENH: check maximum record length when generating db

docs/pragma_usage.rst, docs/release_notes.rst, pytmc/bin/debug.py, pytmc/bin/stcmd.py, pytmc/parser.py, pytmc/pragmas.py, pytmc/tests/test_motion.py, pytmc/tests/test_xml_collector.py
Closes #223 
Fixes as a follow-up to #240 
Closes #242 
Feature point: extends pragma syntax, allowing for forward-references to sub-items (e.g., member variables of function blocks).
If `fbTest` contains a member variable `variable1` with a different `io` setting than desirable for the particular use case, this PR now allows for changing it by way of adding this pragma:
```
variable1.io: io
```
with the overall syntax of `[member].[sub-member].pragma_key: pragma_value`.
Started off with a slightly modified `kfe-motion.tmc` file ([here](https://gist.github.com/klauer/ec6bb07179fafdccc9cacd04f56476a9)), setting `arrStates.array: 1..4` "externally".
Appears to be working locally, but I suspect I won't be catching all edge cases. Going to re-run pytmc on some IOCs and compare the output now. …
=> ENH: subitem pragma support

docs/terminal_usage.rst, pytmc/bin/pytmc.py, pytmc/bin/template.py, pytmc/parser.py, pytmc/tests/test_commandline.py
First pass at #209
Additionally enables projects such as https://github.com/pcdshub/plc-summary.
Fortunately this is still consistent with what I had intended with ads-deploy (at least according to my old comment, as I didn't recall): https://github.com/pcdshub/ads-deploy/blob/c7048848e284a5ba35245fe2f5943824fa4a6065/ads_deploy/docs.py#L11-L13
=> ENH: add `pytmc template` tool

pytmc/bin/template.py
=> ENH: add git information to the template tool, if available

.travis.yml, README.rst, conda-recipe/meta.yaml, docs/index.rst, docs/installation.rst, docs/release_notes.rst, run_tests.py
Closes #259 
Will require new release to fix PyPI, but in principle this should do it.
Done using `git sed` (*) so should double check I didn't do anything terribly wrong.
(*) 
`.gitconfig`
```
[alias]
sed=!git grep -z --full-name -l '.' | xargs -0 sed -i '' -e
```
=> MNT: fix remaining slaclab references

docs/pragma_usage.rst, pytmc/pragmas.py, pytmc/record.py, pytmc/tests/test_xml_collector.py
Closes #261 
Integer and floating point values may have an EPICS-side scaling applied.
Example:
scale: 3.0
offset: 1.0
Values will be scaled according to the following:
readback_value = raw_value * scale + offset
setpoint_value = (user_value - offset) / scale
Note:
If either ``scale`` or ``offset`` are applied to an integer symbol, the
generated EPICS record type will no longer be a "long" integer input/output
record but rather change to an analog input/output record.
Keep this in mind if using advanced "field" directives in your pragmas.
If unspecified, ``scale`` will be assumed to be 1.0 and ``offset`` 0.0.
=> ENH: add scale and offset support for ints and floats

.travis.yml, pytmc/record.py, pytmc/tests/test_xml_collector.py
Background
------------
`link:` allows for pytmc to generate records that push PV data _into_ the PLC from other IOCs.
Status quo
-------------
pytmc currently supports linking numeric scalar values (with corresponding records that have the `OMSL`/`DOL` fields). 
This doesn't include strings.
This PR
--------
* This PR adds in an additional record to glue the "to-plc output" waveform record
* Using the `lso` record, we have long string output support (> 40 chars)
* Closes #267 (further reference/record example there)
I'm going to build up the PLC side of this before finalizing this PR and making it ready-for-review, as one may influence the other.
Pairs with https://github.com/pcdshub/lcls-twincat-general/pull/53
Example diff
-------------
pytmc master vs this PR
```diff
diff --git …
```
=> ENH: link strings

.travis.yml, pytmc/bin/stcmd.py, pytmc/code.py, pytmc/parser.py
* Some things sitting around uncommitted for a while
* Some additional type hint cleanups/fixes
* One (probably never-hit) bug fixed: "lines_between" had a logic error that would not search for the start marker if the end marker was found before it
* Reduced memory consumption slightly by not caching the xml element on every TwincatItem
* Add `EnumerationTextList` with `get_source_code` support; as previously these translatable types were missing
So there are some unfortunate things in the way that the parser breaks out `TwincatItem` classes. Here's the background on why the parser items are as they are:
* I wanted easy mappings of TwinCAT `<xml-tag>` to Python class, where methods and properties could then be context-specific (e.g., _give me the source code of the GVL_)
* I wanted things …
=> MNT: miscellaneous minor fixes and tweaks

pytmc/__main__.py, pytmc/bin/code.py, pytmc/parser.py
Closes #270 
Closes #211 
~The actual result here may not be "valid" IEC 61131-3 method/action definition code.
Why? Well, TwinCAT, for example, does not store the source code of methods in plain text along with its respective function block. It has an XML container that describes a hierarchy of "POU contains actions, methods, declaration, implementation".
So in the method definition itself, `METHOD methodname` there does not need to be a reference to the containing POU.~
~What is suggested and implemented here is the only thing I can think of - aside from giving up on plain text altogether for these - is to prefix methods and actions with `FB_Name` - e.g., `FB_Name.MethodName`.~
~This will have consequences downstream for anything desiring to parse pytmc's "code" output (it'll be vital …
=> ENH: include actions, methods, and properties in `pytmc code`

.gitmodules, pytmc/bin/stcmd.py, pytmc/bin/template.py
* `evalcontextfilter` was deprecated in JInja2 and removed in 3.1
* We used this to wrap our filters but didn't use the context, so I've just removed such references
* Templates still working during local testing with Jinja2 3.1:
```
pytmc/tests/test_commandline.py::test_template_basic[/Users/klauer/Repos/pytmc/pytmc/tests/projects/lcls-plc-kfe-motion/plc-kfe-motion/plc-kfe-motion.tsproj] PASSED [ 15%]
pytmc/tests/test_commandline.py::test_template_basic[/Users/klauer/Repos/pytmc/pytmc/tests/projects/lcls-plc-kfe-gmd-vac-ext-io/plc/plc-kfe-gmd-vac/plc-kfe-gmd-vac.tsproj] PASSED [ 23%]
pytmc/tests/test_commandline.py::test_template_basic[/Users/klauer/Repos/pytmc/pytmc/tests/projects/lcls-plc-kfe-xgmd-vac/plc/plc-kfe-xgmd-vac/plc_kfe_xgmd_vac.tsproj] PASSED [ 30%] …
```
=> CLN: remove evalcontextfilter usage

pytmc/record.py, pytmc/tests/test_xml_collector.py
Closes #282 
Prior to this PR, we are erroneously limited to 2Hz updates for all IOC->PLC PV links due to the 0.5 second SCAN rate configured for linked records. What we want is the IOC to write to the PLC on *every* update, and failing that at 2Hz.
* A `CPP` link means "channel access link which causes processing (when the monitor is fired), **only if** the record's scan field is set to Process Passive
* A `CP` link means "channel access link which causes processing (when the monitor is fired), regardless of the record's SCAN field
In our case, we want the linked record to cause processing on *every* update. This is how the mechanism is supposed to work with pytmc writing values from the IOC to the PLC.
=> FIX: CP link instead of CPP link

pytmc/record.py, pytmc/tests/ads.dbd
Closes #286 
* Updates the vendored `ads.dbd` to the ads-ioc R0.5.0 database definition file (this makes the diff line count look massive...)
* This is used in the test suite to verify the fields that we have set
* Adds description field to autosave for all records, input and output
* Adds alarm severity and limit fields to autosave for all relevant input and output records
* Adds control limit (drive low/high) fields to autosave for relevant output records
```python
import whatrecord
dbd = whatrecord.parse("pytmc/tests/ads.dbd")
for rtyp in ("ai", "ao", "bi", "bo", "mbbi", "mbbo", "longin", "longout", "waveform"):
print(f"\n\n{rtyp}\n{'-' * len(rtyp)}")
for name, fld in dbd.record_types[rtyp].fields.items():
if fld.prompt and "sev" in fld.prompt.lower():
print(f'"{name}",  # …
```
=> ENH: autosave field additions

docs/conf.py, pytmc/parser.py
Closes #288 
@ghalym discovered this which I summarized in #288 
`Project` is an overloaded tag in TwinCAT XML files. It can be:
* A `TcSmProject`
- The `.tsproj` root node
* A top-level project -> `TopLevelProject`
- This contains PLCs, motion, safety, IO
- Found in `.tsproj` under `TcSmProject`
* An embedded PLC project -> `Plc`
- Found in `.tsproj`
- `Project` inside a `Plc` node underneath a `TopLevelProject`
* An external PLC project reference -> `Plc`
- Marked with "File" or "PrjFilePath" attributes
- Found under `TcSmProject` / `TopLevelProject` / `Plc`
* The top-level of an external `.plcproj` project -> `PlcProject`
- Found in the `.plcproj` file referenced via `TcSmProject` /
`TopLevelProject` / `Plc`
* A safety PLC (found under a `Safety` node) -> `SafetyPlc`
- Found under …
=> FIX: safety PLCs are located in _Config/SPLC

pytmc/bin/stcmd.py, pytmc/tests/test_motion.py, pytmc/tests/tmc_files/tc_mot_example.tmc
Previously, the `@` macro substitution machinery did not run for the st.cmd motor records.
This PR removes the duplicated logic and paths us through the same record generation code used for general-purpose db files. This fixes the aforementioned issue.
See https://github.com/pcdshub/lcls-plc-example-motion/pull/10/commits/15bc045b52321a7968d50101f573b8d4a7148177 for mild proof that this works. I've conflated the fix here with some unrelated edits to make my pvnames shorter (they were too long) and edits I made to add parentheses in my substitution lines, but you can see the `@` symbol turning into a `$`
I've also added a unit test.
=> FIX: macro sub in st.cmd motor records

pytmc/parser.py, pytmc/tests/test_integrations.py, pytmc/tests/test_parsing.py
Without this PR, type aliases don't "see" the pragmas from their type source.
This means the database is generated with large numbers of missing records if we keep using the old names (DUT_MotionStage, DUT_PositionState)
Database generation diff: https://github.com/pcdshub/lcls-plc-example-motion/pull/10/commits/6bbae6b30127325e0c5d012191152e551f4600b0
=> ENH: include type alias source pragmas in db generation

conda-recipe/meta.yaml, pytmc/parser.py
When TwinCAT is not configured according to our setup guide (specifically independent project files), the user gets a confusing traceback while attempting to generate an IOC startup script that links NC axes back to their `DUT_MotionStage` (or `ST_MotionStage`):
```
Traceback (most recent call last):
File "C:\miniconda\envs\ads-deploy-2.9.1\lib\site-packages\jinja2\environment.py", line 466, in getitem
return obj[argument]
TypeError: 'Symbol_DUT_MotionStage' object is not subscriptable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "C:\miniconda\envs\ads-deploy-2.9.1\Scripts\pytmc-script.py", line 33, in <module>
sys.exit(load_entry_point('pytmc', 'console_scripts', 'pytmc')())
File "c:\repos\pytmc\pytmc\bin\pytmc.py", line 91, …
```
=> MNT: warn on misconfiguration of TwinCAT IDE/project settings

pytmc/bin/template.py, pytmc/tests/test_commandline.py
Closes https://github.com/pcdshub/pytmc/issues/299
For `pytmc template`, always use a colon delimiter, regardless of the platform.
That means that the input file should be of the form: `input_filename:output_filename` on Windows, Mac, Linux.
(Previously this could have been `input_filename;output_filename` on Windows)
Some special handling is then required to parse these appropriately, since Windows paths can have colons in them. Two absolute paths could then look like `C:\a\b.c.txt:C:\d\e\f.txt` - confusingly enough. The algorithm here checks to see if the first file exists in the case where the delimiter itself is ambiguous.
A quicker hack/fix is already out on plcprog-console: (`filename.rsplit(":", 1)`) - because we only use one absolute filename, the output is relative to the IOC …
=> REF: always use colon delimiter for `pytmc template`

pytmc/bin/template.py, pytmc/tests/test_commandline.py
(Short follow-up PR to #320 )
``pytmc template``, which takes a TwinCAT project and jinja template source
code to generate project-specific output, now expects all platforms to use
the same delimiter (``":"``) for template filename patterns. Examples include:
* Read template from ``a.template`` and write expanded version to ``a.txt``:
``pytmc template my.tsproj --template a.template:a.txt``
* Read template from ``a.template`` and write results to standard output:
``pytmc template my.tsproj --template a.template``       **This PR fixes this scenario for back-compat purposes**
* Read template from standard input and write results to standard output:
``pytmc template my.tsproj --template -``
* Read template from standard input and write results to ``/path/to/a.txt``:
``pytmc template …
=> MNT: back-compat for 'pytmc template' delimiter-less filename

docs/source/release_notes.rst
* Add release notes for v2.16.0
<hr/>
<hr/>
* Fix old release notes as Sphinx was complaining when I built locally
* Rendering appears to be better, at least:
<hr/>
<hr/>
=> DOC: update release notes for v2.16.0

pytmc/templates/asyn_standard_record.jinja2, pytmc/tests/test_record.py
https://jira.slac.stanford.edu/browse/ECS-5005
This adds an ASG field with the value NO_WRITE to any EPICSRecord with direction input in the jinja database template. This access security group will be added to a new version of ads-ioc and will only allow reading, not writing to pvs. 
https://github.com/pcdshub/ioc-common-ads-ioc/pull/103
=> DEV: Making _RBV PVs read-only

conda-recipe/meta.yaml
Noticed that conda tests were failing because setuptools wasn't implicitly present in #332.
=> Adding setuptools_scm to conda recipe

pytmc/pragmas.py, pytmc/record.py, pytmc/tests/test_xml_collector.py
Meant to close #327. I made two small changes for this to work
- In from chain, I moved the data_type.is_string in front of the data_type.is_array or chain.last.array_info so that arrays will not use WaveformRecordPackage.
- I handle string arrays as a complex type instead of a non-complex type so that a pv is made for each array index
=> Support for arrays of strings

pytmc/parser.py
This is to address https://jira.slac.stanford.edu/browse/ECS-6685
This works offline and doesn't seem to break the test suite
I'd like to deploy this as a tag for use in the CI builds
=> FIX: workaround for files that end up in strange subfolders
